### PR TITLE
Variable network adapter

### PR DESCRIPTION
**Pull request by DeviaVir**

### CODE REVIEW

**Comment by DeviaVir** [comment]
ping @beeryardtech + @travisgoldie (if you guys are too busy to handle these sorts of things, I would happily volunteer to help out!)

**Comment by beeryardtech** [comment]
Thanks for the changes. I have applied them and added some more. Updating the fork now.

**Comment by beeryardtech** [comment]
Implemented this differently using a PR from @edouard-lopez.  I will go in there and also make it configurable (like you have here). Thanks for the PR!

**Comment by beeryardtech** [comment]
Thanks again for the help (and the ping :)). Please play around with the newest version and let me know what you think

**Pull request closed without merging**
